% test Laplace exterior BVP on sphere
% 
% 

clear all

addpath ./spharm/; 

p=16; % 3d spherical harmonics order
S = mySurfaceSph(p);
% self eval mat
[SMat, SpMat, DMat] = kernelDLap(S); % Laplace SLP, SLPn, DLP self eval matrix

% quadr nodes
s.x = [S.cart.x,S.cart.y,S.cart.z]'; % source on the boundary surface
s.nx = [S.geoProp.nor.x S.geoProp.nor.y S.geoProp.nor.z]';
% quadr weights (GL x Trapezoidal)
[~, gwt]=g_grid(p+1);
wt = pi/p*repmat(gwt', 2*p, 1)./sin(gl_grid(p));
s.w = (S.geoProp.W.*wt(:))'; 

% Dirichlet BVP generated by an interior point source
y_source.x = [0.1;0.2;-0.3]; y_source.w = 1; pt_source = [1];
Ahom = Lap3dSLPmat(s,y_source);
rhs = Ahom*pt_source; 

% solve
mu = (eye(size(DMat))/2 + DMat + SMat)\rhs(:);

% verify solution
t.x = [s.x + s.nx, s.x + 3/4*s.nx, s.x + 1/2*s.nx];
fhom = Lap3dSLPmat(t,y_source)*pt_source;
fnum = (Lap3dSLPmat(t,s)+Lap3dDLPmat(t,s))*mu;

err = abs(fnum-fhom)/max(abs(fnum));

%
figure(1),clf,
scatter3(t.x(1,:),t.x(2,:),t.x(3,:),10,log10(err),'filled');
colorbar, axis equal, hold on
surf(reshape(s.x(1,:),p+1,[]),reshape(s.x(2,:),p+1,[]),reshape(s.x(3,:),p+1,[]))
caxis([-12 0])
title(['Nystrom SLP+DLP p=' num2str(p) ', ' num2str((p+1)*2*p) 'x' num2str((p+1)*2*p) ', rank ' num2str((p+1)*2*p)], 'FontSize', 16)
% figure(1),print -dpng -r600 lap_nystrom.png; system('convert -trim lap_nystrom.png eps2:lap_nystrom.eps');

%%%
% val2coefs & coefs2vals
shc = shAna(mu); % vals2coefs
[u,v] = gl_grid(p);
mu2 = sumBasis(shc,'Ynm',1,u,v); % coefs2vals
rhs2 = (eye(size(DMat))/2 + DMat + SMat)*mu2;
err_rhs = abs(rhs2-rhs);
% val2coefsMat & coefs2valsMat
shcMat = shAna(eye(2*p*(p+1)));
shvMat = sumBasis(eye(size(shcMat,1)),'Ynm',false,u,v);
% Galerkin SLP mat
GSMat = shcMat*(SMat)*shvMat; % Galerkin SMat, rank 1 null space?
% solve
mucS = GSMat\(shcMat*rhs(:)); % null space does not seem to matter
% muc to mu (coefs2vals)
muS = real(shvMat*mucS); % imaginary part ~ 1e-17
% eval & err of SLP
fnumS = Lap3dSLPmat(t,s)*muS;
errS = abs(fnumS-fhom)/max(abs(fnum));

figure(2),clf,
scatter3(t.x(1,:),t.x(2,:),t.x(3,:),10,log10(errS),'filled');
colorbar, axis equal, hold on
surf(reshape(s.x(1,:),p+1,[]),reshape(s.x(2,:),p+1,[]),reshape(s.x(3,:),p+1,[]))
caxis([-12 0])
title(['Galerkin SLP p=' num2str(p) ', ' num2str((p+1)^2) 'x' num2str((p+1)^2) ', rank ' num2str((p+1)^2-1)], 'FontSize', 16)
% figure(2),print -dpng -r600 lap_galerkin.png; system('convert -trim lap_galerkin.png eps2:lap_galerkin.eps');


keyboard
